-- B+ HR schema aligned with the application specification.
-- Applied to the connected Supabase project as migrations complete_bplus_hr_schema and enable_rls_on_bplus_new_tables.

create table if not exists public.store_hours (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  is_closed boolean not null default false,
  schedule_type text not null default 'continuous' check (schedule_type in ('continuous','split')),
  open_time time, close_time time,
  morning_open time, morning_close time,
  afternoon_open time, afternoon_close time,
  min_staff integer not null default 0 check (min_staff >= 0),
  min_opening integer not null default 0 check (min_opening >= 0),
  min_closing integer not null default 0 check (min_closing >= 0),
  min_lunch integer check (min_lunch is null or min_lunch >= 0),
  unique(location_id, day_of_week)
);

create table if not exists public.store_date_overrides (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  override_date date not null,
  is_closed boolean not null default false,
  schedule_type text not null default 'continuous' check (schedule_type in ('continuous','split')),
  open_time time, close_time time,
  morning_open time, morning_close time,
  afternoon_open time, afternoon_close time,
  min_staff integer not null default 0 check (min_staff >= 0),
  min_opening integer not null default 0 check (min_opening >= 0),
  min_closing integer not null default 0 check (min_closing >= 0),
  min_lunch integer check (min_lunch is null or min_lunch >= 0),
  unique(location_id, override_date)
);

alter table public.employees add column if not exists phone text;
alter table public.employees add column if not exists password_changed_at timestamptz;
alter table public.employees add column if not exists general_skill integer check (general_skill between 1 and 5);
alter table public.employees add column if not exists tintometro boolean not null default false;
alter table public.employees add column if not exists keys_skill boolean not null default false;
alter table public.employees add column if not exists forklift_skill boolean not null default false;
alter table public.employees add column if not exists cash_skill boolean not null default false;
alter table public.employees add column if not exists wood_cut_skill boolean not null default false;
alter table public.employees add column if not exists kasanova_skill boolean not null default false;
alter table public.employees add column if not exists contract_type text;
alter table public.employees add column if not exists weekly_hours numeric(5,2);
alter table public.employees add column if not exists break_type text check (break_type is null or break_type in ('fixed','flexible'));
alter table public.employees add column if not exists break_start time;
alter table public.employees add column if not exists break_end time;
alter table public.employees add column if not exists break_minutes integer;
alter table public.employees add column if not exists sunday_policy text check (sunday_policy is null or sunday_policy in ('every_2','every_3','all','none'));
alter table public.employees add column if not exists recovery_hours numeric(6,2) not null default 0;
alter table public.employees add column if not exists exit_18_enabled boolean not null default false;
alter table public.employees add column if not exists exit_18_days integer[];
alter table public.employees add column if not exists fixed_rest_days integer[];
alter table public.employees add column if not exists sunday_comp_rest_days integer[];
alter table public.employees add column if not exists mobile_location_ids bigint[];
alter table public.employees add column if not exists employment_status text not null default 'active' check (employment_status in ('active','absent','vacation','sick'));
alter table public.employees add column if not exists include_in_shifts boolean not null default false;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null, provider text, description text,
  mandatory boolean not null default false,
  status text not null default 'planned' check (status in ('planned','active','completed','cancelled')),
  created_at timestamptz not null default now()
);
create table if not exists public.course_sessions (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  session_date date not null, start_time time, end_time time
);
create table if not exists public.course_participants (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.course_sessions(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  status text not null default 'invited' check (status in ('invited','confirmed','absent')),
  unique(session_id, employee_id)
);
create table if not exists public.shift_weeks (
  id bigint generated by default as identity primary key,
  week_start date not null,
  location_id bigint references public.locations(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft','published')),
  snapshot jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_shifts_employee_date on public.shifts(employee_id, shift_date);
create index if not exists idx_absences_employee_dates on public.absences(employee_id, start_date, end_date);
create index if not exists idx_notifications_employee_unread on public.notifications(employee_id, read_at);
create index if not exists idx_app_notifications_recipient_unread on public.bplus_app_notifications(recipient_employee_id, read_at);
create index if not exists idx_push_subscriptions_employee on public.bplus_push_subscriptions(employee_id);
create index if not exists idx_store_overrides_date on public.store_date_overrides(location_id, override_date);

alter table public.store_hours enable row level security;
alter table public.store_date_overrides enable row level security;
alter table public.courses enable row level security;
alter table public.course_sessions enable row level security;
alter table public.course_participants enable row level security;
alter table public.shift_weeks enable row level security;
